Revert "Save changes before switching branches"
This reverts commit 961ee22685875e58d57dddd8e04ba1a9b1fd5655.

CONFLICT (modify/delete): __pycache__/preprocess.cpython-310.pyc deleted in HEAD and modified in parent of 961ee22 (Save changes before switching branches).  Version parent of 961ee22 (Save changes before switching branches) of __pycache__/preprocess.cpython-310.pyc left in tree.
error: could not revert 961ee22... Save changes before switching branches
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git revert --continue".
hint: You can instead skip this commit with "git revert --skip".
hint: To abort and get back to the state before "git revert",
hint: run "git revert --abort".
error: Reverting is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: revert failed